jobs:
  - name: plv2-man1
    type: manifest
    steps:
      - IN: plv2-image1
      - IN: triggerv2sp1
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
  
  - name: release-version1
    type: release
    steps:
      - IN: plv2-version
      - IN: plv2-man1
      - IN: triggerv2sp2
      - TASK: managed
        bump: major
        
  - name: plv2-ddcdeploy
    type: ddcDeploy
    steps:
      - IN: plv2-man1
      - IN: ddc-cluster
      
 # - name: b-mon-dcl
  #  type: dclDeploy
   # steps:
    #  - IN: plv2-manifest2
     # - IN: dcl-cluster
      #- TASK: managed

  - name: plv2-ecsdeploy
    type: ecsDeploy
    steps:
      - IN: plv2-man1
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: plv2-gkedeploy
    type: gkeDeploy
    steps:
      - IN: plv2-man1
      - IN: gke-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: plv2-tripubdeploy1
    type: tripubDeploy
    steps:
      - IN: plv2-man1
      - IN: tripub-cluster3
      
