jobs:
  - name: plv2-man2
    type: manifest
    steps:
      - IN: plv2-image1
      - IN: triggerv2sp1
    #on_success:
     # - echo 'this is on_success step of dv-man of type manifest'
    #on_failure:
     # - echo 'this is on_failure step of dv-man of type manifest'
  
#  - name: release-version2
 #   type: release
  #  steps:
   #   - IN: plv2-version
    #  - IN: plv2-man2
    #  - IN: triggerv2sp2
     # - TASK: managed
    #    bump: major
        
 # - name: plv2-ddcdeploy1
  #  type: ddcDeploy
   # steps:
    #  - IN: plv2-man2
     # - IN: ddc-cluster
      
#  - name: b-mon-dcl1
 #   type: dclDeploy
  #  steps:
   #   - IN: plv2-man2
    #  - IN: cluster-dcl
    #  - TASK: managed

  - name: plv2-ecsdeploy1
    type: ecsDeploy
    steps:
      - IN: plv2-man2
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

#  - name: plv2-gkedeploy1
 #   type: gkeDeploy
  #  steps:
   #   - IN: plv2-man2
    #  - IN: gke-cluster
     # - TASK: managed
      #  deployMethod: upgrade

 # - name: plv2-tripubdeploy2
  #  type: tripubDeploy
   # steps:
    #  - IN: plv2-man2
     # - IN: tripub-cluster3
      
