triggers:
   - name: triggerv2sp1
     type: trigger
     version:
       counter: 688
   - name: triggerv2sp2
     type: trigger
     version:
       counter: 17
       
   - name: triggerv2sp3
     type: trigger
     version:
       counter: 165
